#!/bin/sh


## Copyright (c) 2011 Atticus White (www.atticuswhite.com)
## Github project available at: https://github.com/ajwhite/Apache-Configuration-Builder
##     
## Permission is hereby granted, free of charge, to any person obtaining
## a copy of this software and associated documentation files (the
## "Software"), to deal in the Software without restriction, including
## without limitation the rights to use, copy, modify, merge, publish,
## distribute, sublicense, and/or sell copies of the Software, and to
## permit persons to whom the Software is furnished to do so, subject to
## the following conditions:
## 
## The above copyright notice and this permission notice shall be
## included in all copies or substantial portions of the Software.
## 
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
## EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
## MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
## NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
## LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
## OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
## WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.



VHOST_FILE=/etc/apache2/extra/httpd-vhosts.conf
HOST_FILE=/etc/hosts



if [[ $UID != 0 ]]; then
	echo "This script requires root"
	echo "sudo $0 $*"
	exit 1
fi

echo "##################################################"
echo "##################################################"
echo "########  APACHE CONFIGURATION BUILDER  ##########"
echo "########        by Atticus White        ##########"
echo "##################################################"
echo "##################################################"


currentDir=${PWD}
currentDir="$currentDir/"





function createIndex {
	indexFile="$projectDirectory/index.html"
	touch $indexFile
	chown "$SUDO_USER" "$indexFile"
	chmod 775 $indexFile
	
	echo "<h2>It works!</h2>" >> $indexFile
	echo "<code>" >> $indexFile
	echo "Project Name: $projectName<br/>" >> $indexFile
	echo "Project Location: $projectDirectory<br/>" >> $indexFile
	echo "Project Domain: $projectDomain<br/>" >> $indexFile
	echo "<br/><br/><br/>" >> $indexFile
	echo "<small>" >> $indexFile
	echo "<a href=\"https://github.com/ajwhite/Apache-Configuration-Builder\" target=\"_blank\">" >> $indexFile
	echo "Generated by Atticus White's Apache Configuraiton Builder</a>" >> $indexFile
	echo "</small>" >> $indexFile
	echo "</code>" >> $indexFile
	
}






## PROJECT NAME
##read -p "New Project Name: " projectName
read -p "Project Location: " projectDirectory


## PROJECT DOMAIN NAME
read -p "New Domain Name: " projectDomain


echo "Please confirm:"
echo "Project Directory: $projectDirectory"
echo "Project Domain: $projectDomain"
read -p "Are these correct? (y/n) " validProjectTerms

if [ "$validProjectTerms" != "y" ]; then
	exit 1
fi


if [ ! -d "$projectDirectory" ]; then
	read -p "Directory does not exist, would you like to create it? (y/n): " createDirectory
	
	if [ "$createDirectory" == "y" ]; then
		echo "Creating Directory $projectDirectory"
		mkdir $projectDirectory
		chown "$SUDO_USER" "$projectDirectory"
		chmod 775 $projectDirectory
	fi
fi

read -p "Install Wordpress? (y/n) " installWordpress

if [ "$installWordpress" == "y" ]; then
	
	cd $projectDirectory
	
	wget http://wordpress.org/latest.zip
	rm latest.zip
	
	echo "Wordpress downloaded, unzipped, and archive removed"
	
	read -p "Create database for wordpress? (y/n) " createWordpressDb
	
	if [ "$createWordpressDb" == "y" ]; then
		source ~/.bash_profile
		read -p "Name for new database: " databaseName
		read -p "MySQL username: " databaseUsername
		read -p "MySQL password: " databasePassword
		sudo /usr/local/mysql/support-files/mysql.server start
		
		echo "CREATE DATABASE $databaseName" | mysql -u $databaseUsername -p$databasePassword
	fi


fi



## HOST FILE
echo "127.0.0.1	$projectDomain"  >> $HOST_FILE


echo "


## $projectName
#
<VirtualHost *:80>
        ServerAdmin     contact@atticuswhite.com
        DocumentRoot    \"$projectDirectory\"
        ServerName      $projectDomain
        ErrorLog        \"/private/var/log/apache2/$projectDomain-error_log\"
        CustomLog       \"/private/var/log/apache2/$projectDomain-access_log\" common

        <Directory \"$projectDirectory\">
                Options Indexes Includes FollowSymLinks MultiViews
                AllowOverride AuthConfig FileInfo
                Order allow,deny
                Allow from all
        </Directory>
</VirtualHost>" >> $VHOST_FILE


apachectl restart

open -a "Google Chrome" "http://$projectDomain"